apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-builder
  annotations:
    github.com/project-slug: igormattiolli/react-builder
spec:
  type: other
  lifecycle: unknown
  owner: Manager
